security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            lazy: true

            form_login:
                login_path: app_login
                check_path: app_login

            login_throttling:
                max_attempts: 2

            entry_point: form_login

            logout:
                path: app_logout
                target: /

    access_control:
        - { path: ^/location, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_USER:
            - ROLE_LOCATION_INDEX
            - ROLE_LOCATION_SHOW

        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_LOCATION_NEW
            - ROLE_LOCATION_EDIT
            - ROLE_LOCATION_DELETE
            - ROLE_MEASUREMENT_INDEX
            - ROLE_MEASUREMENT_SHOW
            - ROLE_MEASUREMENT_NEW
            - ROLE_MEASUREMENT_EDIT
            - ROLE_MEASUREMENT_DELETE
